SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\ATMEL
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=AT80C51RD2
SET CPU_VENDOR=Microchip
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02625A00
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\ds1307.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\i2c.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\lcd.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"C:\Keil_v5\C51\BIN\BL51.EXE" @".\Objects\GIAOTH~2.LNP"
"C:\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\giaothongp" 
